VERSION: 2

DATASETS:
  TRAIN: ("cater",)
  TEST: ("cater_test",)

MODEL:
  SEPARATE_ATTR_ON: False
  ROI_HEADS:
    NAME: "CaterROIHeads"
  ROI_COORDINATE_HEAD:
    USE_BACKBONE_FEATURES: True
    IN_FEATURES: ["p2","p3","p4","p5"]
    IMG_SIZE: (240, 320)
    POOLER_RESOLUTION: (7,7)
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: "ROIAlignV2"
    HIDE_IMG_SIZE: (128, 128)
    NUM_STACKED_CONVS: 2 
    # larger receptive field
    CONV_HEAD_KERNEL_SIZE: 3
    DILATION: 2
    CHANNEL_DECREASE_RATIO: 5

SOLVER:
    GAMMA: 0.8
    STEPS: (1500, 2500, 3500)
    MAX_ITER: 4000
    BASE_LR: 0.01
    CHECKPOINT_PERIOD: 2000

INPUT:
  MIN_SIZE_TRAIN: (640,)
  MIN_SIZE_TEST: 640
  RANDOM_FLIP: "none"