VERSION: 2

DATASETS:
  TRAIN: ("cater",)
  TEST: ("cater_test",)

MODEL:
  SEPARATE_ATTR_ON: False
  ROI_HEADS:
    NAME: "CaterROIHeads"
  ROI_COORDINATE_HEAD:
    USE_BACKBONE_FEATURES: False 
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    IMG_SIZE: (240, 320)
    POOLER_RESOLUTION: 128
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: "ROIAlignV2"
    HIDE_IMG_SIZE: (96, 128)
    NUM_STACKED_CONVS: 5
    DILATION: 2

SOLVER:
    GAMMA: 0.8
    STEPS: (1500, 2500, 3500)
    MAX_ITER: 4000
    BASE_LR: 0.01
    CHECKPOINT_PERIOD: 2000

INPUT:
  MIN_SIZE_TRAIN: (640,)