VERSION: 2
MODEL:
  SEPARATE_ATTR_ON: False
  ROI_HEADS:
    NAME: "CaterROIHeads"
  ROI_COORDINATE_HEAD:
    USE_BACKBONE_FEATURES: False
    IN_FEATURES: []
    IMG_SIZE: (240, 320)
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlignV2"