VERSION: 2
MODEL:
  SEPARATE_ATTR_ON: False
  ROI_HEADS:
    NAME: "CaterROIHeads"
  ROI_COORDINATE_HEAD:
    USE_BACKBONE_FEATURES: False
    IN_FEATURES: []
    IMG_SIZE: (240, 320)
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: "ROIAlignV2"
    HIDE_IMG_SIZE : (128, 128)

INPUT:
  MIN_SIZE_TRAIN: (640,)